config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'apply', to: 'pages#apply', as: 'apply'
  get 'thank-you', to: 'pages#thanks', as: 'thanks'
  get 'start', to: 'pages#start', as: 'start'
  get 'magic-login', to: 'pages#magic_login', as: 'magic_login'

  devise_for :users
  get 'logout', to: 'pages#logout', as: 'logout'

  resources :subscribe, only: [:index]
  # resources :dashboard, only: [:index]

  get 'dashboard', to: 'dashboard#index'
  get 'project_updates/new', to: 'project_updates#new'
  
  resources :user_submissions, only: [:create]
  resources :projects, only: [:update]

  resources :account, only: [:index, :update]
  resources :billing_portal, only: [:create]
  match '/billing_portal' => 'billing_portal#create', via: [:get]
  match '/cancel' => 'billing_portal#destroy', via: [:get]

  # static pages
  pages = %w(
    privacy terms
  )

  pages.each do |page|
    get "/#{page}", to: "pages##{page}", as: "#{page.gsub('-', '_')}"
  end

  namespace :admin do
    get '/', to: 'pages#dashboard'
    resources :user_submissions, only: [:update]
  end
  

  # admin panels
  # authenticated :user, -> user { user.admin? } do
  #   namespace :admin do
  #     resources :dashboard, only: [:index]
  #     resources :impersonations, only: [:new]
  #     resources :users, only: [:edit, :update, :destroy]
  #   end

  #   # convenience helper
  #   get 'admin', to: 'admin/dashboard#index'
  # end
end

app/views/admin/pages/dashboard.html.erb
<%= render partial: "shared/heading", locals: {title: "Admin Panel", description: "Approve or reject applicants here." } %>

<div class="px-4 sm:px-6 lg:px-8">
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Name</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Email</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Website</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Content</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Status</th>
                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
                  <span class="sr-only">Edit</span>
                </th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 bg-white">

            <% @user_submissions.each do |user_submission| %>
              <tr>
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"><%= user_submission.name %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= user_submission.email %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= user_submission.website %></td>
                <td class="px-3 py-4 text-sm text-gray-500 max-w-xs"><%= user_submission.text %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
                    <div>
                      <%= form_for user_submission, url: admin_user_submission_path(user_submission) do |form| %>
                        <select id="user_submission_status" name="user_submission[status]" class="mt-2 block rounded-md border-0 py-1.5 pl-3 pr-10 text-gray-900 ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-indigo-600 sm:text-sm sm:leading-6">
                            <option <%= "selected" if user_submission.status.nil? %> >Pending</option>
                            <option <%= "selected" if user_submission.status == "Approve" %> >Approve</option>
                            <option <%= "selected" if user_submission.status == "Reject" %> >Reject</option>
                        </select>
                        <%= form.submit "Update", class: "w-full text-right text-indigo-600 hover:text-indigo-900" %>
                      <% end %>
                    </div>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>