config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'apply', to: 'pages#apply', as: 'apply'
  get 'thank-you', to: 'pages#thanks', as: 'thanks'
  get 'start', to: 'pages#start', as: 'start'
  get 'magic-login', to: 'pages#magic_login', as: 'magic_login'

  devise_for :users
  get 'logout', to: 'pages#logout', as: 'logout'

  resources :subscribe, only: [:index]
  # resources :dashboard, only: [:index]

  get 'dashboard', to: 'dashboard#index'
  get 'project_updates/new', to: 'project_updates#new'
  
  resources :user_submissions, only: [:create]
  resources :projects, only: [:update]

  resources :account, only: [:index, :update]
  resources :billing_portal, only: [:create]
  match '/billing_portal' => 'billing_portal#create', via: [:get]
  match '/cancel' => 'billing_portal#destroy', via: [:get]

  # static pages
  pages = %w(
    privacy terms
  )

  pages.each do |page|
    get "/#{page}", to: "pages##{page}", as: "#{page.gsub('-', '_')}"
  end

  namespace :admin do
    get '/', to: 'pages#dashboard'
    resources :user_submissions, only: [:update]
  end
  

  # admin panels
  # authenticated :user, -> user { user.admin? } do
  #   namespace :admin do
  #     resources :dashboard, only: [:index]
  #     resources :impersonations, only: [:new]
  #     resources :users, only: [:edit, :update, :destroy]
  #   end

  #   # convenience helper
  #   get 'admin', to: 'admin/dashboard#index'
  # end
end

app/controllers/subscribe_controller.rb
class SubscribeController < ApplicationController
  before_action :authenticate_user!
  before_action :maybe_skip_onboarding

  def index
  end
end

app/views/subscribe/index.html.erb
<%= render partial: "shared/heading", locals: { title: 'Start Trial', description: "Start your 14 day free trial of #{ENV['COMPANY_NAME']}." } %>

<div class="text-center">
  <!-- provide an image to compel user to add payment details -->
  <!-- <%= image_path "", style: "display: inline-block; max-height: 375px;", class: "mt-6 object-center" %> -->
</div>

<p class="mt-12 text-center">Click here to choose a plan and activate your account.</p>
<div class="mt-2 justify-center text-center">
  <div class="text-center inline-flex rounded-md shadow">
    <button onclick="beginSubscription()" type="submit" class="items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700">
      Start Free
    </button>
  </div>
  <div class="mt-2 text-center">
    <!-- bind this element to a live chat tool or mailto address -->
    <a id="open-live-chat" href="#" onclick="return false;" class="font-medium text-indigo-300 hover:text-indigo-500">Still have questions?</a>
  </div>
</div>

<script type="text/javascript">
  var beginSubscription = function() {
    console.log('building subscription...');

    $.ajax({
      url: '<%= billing_portal_index_path %>',
      method: 'POST',
      dataType: 'json',
      data: {},
      success: function(data) {
        console.log('success! portal url: ', data.url)
        window.location.href = data.url;
      },
      error: function(data) {
        window.alert('Sorry, something went wrong. Please try again.');
      }
    })
  }
</script>